### ISSUE TITLE
Error: Cannot find module '../node_modules/tvdb/node_modules/xml2js/lib/xml2js.js'

### ISSUE THREAD

**Issue by arjunmayilvaganan** [ocombe/subNode#9]
```
Starting server
module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/tvdb/node_modules/xml2js/lib/xml2js.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:5:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:514:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
subNode was restarted
Starting server
module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/tvdb/node_modules/xml2js/lib/xml2js.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:5:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:514:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
subNode was restarted
Starting server
module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/tvdb/node_modules/xml2js/lib/xml2js.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:5:19)
    at Object.<anonymous> (/Users/arjunmayilvaganan/Downloads/ocombe-subNode-f0f649d/server/tvdb_lib.js:514:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
subNode has exited.
```

The required file did exist. I also did `npm install xml2js` separately. Not sure what causes this issue.

**Comment by ocombe** [comment]
Wooh I didn't know someone was really using this :)
The development for the 1.x branch has been stopped, you can check the 2.x which is working but still not finished

**Comment by arjunmayilvaganan** [comment]
@ocombe, Thank you. 2.x runs great.

**Comment by ocombe** [comment]
Awesome :)
There are still a few bugs and I need to update the version of Angular 2, but I don't have time to work on that project these days :(
